name: lmn_neston
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  flutter:
    sdk: flutter

  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_storage: ^10.2.9

  #google_sign_in: ^5.2.4
  firebase_messaging: ^11.2.11  
  http: ^0.13.4
  flutter_local_notifications: ^9.4.0

  provider: ^6.0.2
  shared_preferences: ^2.0.13

  uuid: ^3.0.6
  fluttertoast: ^8.0.9  
  file_picker: ^4.5.1  
  #image_picker: ^0.8.4+11
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
    #avatar_glow:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/dummy.jpg
    - assets/girl.jpg
    - assets/logo.png
